import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db";
import { parseJsonField } from "@/lib/utils";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const project = await prisma.project.findUnique({
      where: { id },
      include: {
        analyses: { orderBy: { createdAt: "desc" }, take: 1 },
        questions: { orderBy: { createdAt: "desc" }, take: 8 },
        recommendations: { orderBy: { createdAt: "desc" }, take: 10 },
        diagnoses: { orderBy: { createdAt: "desc" }, take: 6 },
        contentDiffs: { orderBy: { createdAt: "desc" }, take: 1 },
        readinessAudits: { orderBy: { createdAt: "desc" }, take: 1 },
        promptItems: { orderBy: { createdAt: "desc" }, take: 12 },
        sourceMaps: { orderBy: { createdAt: "desc" }, take: 8 },
        experiments: { orderBy: { createdAt: "desc" }, take: 20 },
      },
    });

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    const latestAnalysis = project.analyses[0];
    const strengths = latestAnalysis
      ? parseJsonField<string[]>(latestAnalysis.strengths, [])
      : [];
    const weaknesses = latestAnalysis
      ? parseJsonField<string[]>(latestAnalysis.weaknesses, [])
      : [];
    const nextActions = latestAnalysis
      ? parseJsonField<string[]>(latestAnalysis.nextActions, [])
      : [];

    const markdown = `# GEO Lens Analysis Report

## Project: ${project.name}
**Brand:** ${project.brandName}
**Generated:** ${new Date().toISOString().split("T")[0]}
**Mode:** Demo / Mock

---

## GEO Score Summary

${latestAnalysis
  ? `
| Dimension | Score |
|-----------|-------|
| Entity Clarity | ${latestAnalysis.entityClarity}/100 |
| Answer Coverage | ${latestAnalysis.answerCoverage}/100 |
| Citation Readiness | ${latestAnalysis.citationReadiness}/100 |
| Content Structure | ${latestAnalysis.contentStructure}/100 |
| Freshness Signal | ${latestAnalysis.freshnessSignal}/100 |
| **Total** | **${latestAnalysis.totalScore}/100** |
`
  : "No analysis data available yet."
}

---

## Strengths
${strengths.map((s: string) => `- ${s}`).join("\n")}

## Weaknesses
${weaknesses.map((w: string) => `- ${w}`).join("\n")}

## Priority Actions
${nextActions.map((a: string, i: number) => `${i + 1}. ${a}`).join("\n")}

---

## AI Answer Simulation
${project.questions
  .map(
    (q) =>
      `### Q: ${q.question}
**Intent:** ${q.intent}
**Brand Mentioned:** ${q.brandMentioned ? "Yes" : "No"}

> ${q.simulatedAnswer}

${!q.brandMentioned ? `**Improvement:** ${q.improvement}` : `**Why:** ${q.mentionReason}`}
`
  )
  .join("\n")}

---

## Citation Failure Diagnosis
${project.diagnoses
  .map(
    (d) =>
      `### ${d.failureType.replace(/_/g, " ")} — ${d.severity.toUpperCase()}
- **Evidence:** ${d.evidence}
- **Reason:** ${d.reason}
- **Fix:** ${d.fix}
- **Impact:** ${d.impactedDimension}
`
  )
  .join("\n")}

---

## Content Optimization Recommendations
${project.recommendations
  .map((r) => `### [${r.priority.toUpperCase()}] ${r.title}\n${r.content}`)
  .join("\n\n")}

---

## Before / After GEO Diff
${project.contentDiffs
  .map(
    (d) =>
      `### ${d.sourceLabel}

**Before:**
> ${d.beforeContent.slice(0, 300)}

**After:**
> ${d.afterContent.slice(0, 300)}

**Changes:** ${parseJsonField<string[]>(d.changeSummary, []).join(", ")}
**Rationale:** ${d.rationale}
`
  )
  .join("\n")}

---

## AI Readiness Technical Audit
${
  project.readinessAudits[0]
    ? `**Score:** ${project.readinessAudits[0].totalScore}/100
**Summary:** ${project.readinessAudits[0].summary}`
    : "No audit data available."
}

---

## Prompt Portfolio
${project.promptItems
  .map(
    (p) =>
      `- **[${p.priority}] ${p.prompt}** (${p.intentType}, ${p.funnelStage}, demand: ${p.demandScore})`
  )
  .join("\n")}

---

## Citation Source Map
${project.sourceMaps
  .map(
    (s) =>
      `- **${s.category}:** ${s.coverage} — ${s.gap.slice(0, 100)}`
  )
  .join("\n")}

---

## Experiment Tracker
${project.experiments
  .map(
    (e) =>
      `- **${e.name}** — ${e.status} | Baseline: ${e.baselineScore ?? "—"} | After: ${e.afterScore ?? "—"} | Delta: ${e.delta ?? "—"}`
  )
  .join("\n")}

---

*Generated by GEO Lens — Generative Engine Optimization Platform*
`;

    return NextResponse.json({ markdown, project: { ...project, keywords: parseJsonField(project.keywords, []) } });
  } catch (error) {
    console.error("Report failed:", error instanceof Error ? error.name : "unknown");
    return NextResponse.json(
      { error: "Failed to generate report" },
      { status: 500 }
    );
  }
}
